export const CREATE_LOOP_NOTE = 'CREATE_LOOP_NOTE';
export const DELETE_LOOP_NOTE = 'DELETE_LOOP_NOTE';
export const SET_LOOP_NOTE_RANGE = 'SET_LOOP_NOTE_RANGE';
export const SET_LOOP_RANGE = 'SET_LOOP_RANGE';
export const SET_LOOP_CURRENT_TIME = 'SET_LOOP_CURRENT_TIME';
export const SET_LOOP_PLAY_STATE = 'SET_LOOP_PLAY_STATE';
