export const CREATE_TRACK = 'CREATE_TRACK';
export const SET_TRACK_INSTRUMENT = 'SET_TRACK_INSTRUMENT';
export const SET_TRACK_RECT = 'SET_TRACK_RECT';
export const CREATE_TRACK_LOOP = 'CREATE_TRACK_LOOP';
export const CREATE_TRACK_LOOP_NOTE = 'CREATE_TRACK_LOOP_NOTE';
export const SET_TRACK_LOOP_NOTE_RANGE = 'SET_TRACK_LOOP_NOTE_RANGE';
