export const CREATE_AUDIO_SEGMENT = 'CREATE_AUDIO_SEGMENT';
export const SET_AUDIO_SEGMENT_RANGE = 'SET_AUDIO_SEGMENT_RANGE';
export const MOVE_SEGMENT = 'MOVE_SEGMENT';
export const ADD_NOTE = 'ADD_NOTE';
export const SET_NOTE_RANGE = 'SET_NOTE_RANGE';
